### PR TITLE
Add SLD tag to define arrows direction convention

### PR DESCRIPTION
**Pull request by geojs**
I added a new SLD tag to handle arrows direction according to meteorological convention or oceanographic convention:
https://blogs.esri.com/esri/arcgis/2013/07/17/displaying-speed-and-direction-symbology-from-u-and-v-vectors/
I need this feature to display wave direction from WW3 output:
http://polar.ncep.noaa.gov/waves/products.shtml

### CODE REVIEW

**Comment by guygriffiths** [comment]
I'm happy to include this distinction.  A few things, however:
* We don't merge any pull requests into `master`, except for urgent bugfixes.  This should go into `develop`
* You have implemented the conventions the wrong way around.  The current behaviour of EDAL is that arrows are plotted in the direction of the vector (i.e. what is labelled as oceanographic in your link), and your implementation reverses this for `OCEANOGRAPHIC` instead of `METEOROLOGICAL`.
* I think the labels `DEFAULT` and `METEOROLOGICAL` would be better, since what you've labelled as `OCEANOGRAPHIC` is the actual vector direction.  After which `DEFAULT` should be the default, if no value is specified.
* With these points in mind, we don't need an `oceanographic_arrows.xml` style (since it is already the default behaviour).  Instead you should implement a `meteorological_arrows.xml` style, as well as corresponding ones for the other arrow styles.
* Please do not remove the existing constructors on `ArrowLayer`, `SizedArrowLayer`, and `ColouredSizedArrowLayer`.  Create additional ones instead.
* Wind barbs and upstream dots are a particular styles which already have an implicit meaning.  These styles should not be modified, nor should they accept the `<resc:ArrowDirectionConvention>` tag.

However, bearing all this in mind, along with the fact that you were trying to display data from WW3, I wonder if there is not some other issue at play here?  ncWMS should display WW3 data as you would expect, since we have always used the oceanographic convention for vectors (with the exception of wind barbs, which are their own specific style).  If that's the case, I'm more than happy to work with you to debug the problem - I've not had anyone requesting that ncWMS plot arrows according to the meterological convention, and I've got no pressing reason to do so.

**Comment by geojs** [comment]
It is to display this WW3 data:
ftp://ftp.ifremer.fr/ifremer/ww3/HINDCAST/NORGAS/2013/dp/ww3.201305_dp.nc
Example with "default-arrows" style:
nww3_dp
I guess the arrows direction are in the "wrong way", maybe it use meterological convention ?
Thanks for your help.

**Comment by guygriffiths** [comment]
The problem is that WW3 are using a non-standard convention:
https://forge.ifremer.fr/plugins/mediawiki/wiki/ww3/index.php/En:wave_direction_conventions
which is the opposite of what your link (and my experience of ocean data) suggests.

I'm happy to add this change - if you could implement `vector_meterological_arrows.xml`, `sized_meteorological_arrows.xml`, and `colored_sized_meteorological_arrows.xml` in your branch then I'll merge it in.  Apologies - looking back it wasn't at all clear, but this is what I meant by "the other arrow styles".

**Comment by geojs** [comment]
Thanks you for the link about the non-standard convention with WW3 (my experience with ncwms is limited to display WW3 outputs), I have now a better understanding of direction conventions.
 
I implemented the styles `vector_meterological_arrows.xml`, `sized_meteorological_arrows.xml`, and `colored_sized_meteorological_arrows.xml` in my branch.

**Comment by guygriffiths** [comment]
Great, thanks for that.  I've merged into `develop`, so that'll make the next release.

**Pull request merged**
